name: 'terraform-kubernetes-addons'

on:
  pull_request:
    branches:
      - main
    paths:
      - 'modules/aws/*'
  workflow_dispatch:

jobs:
  renovate-config-check:
    name: 'renovate:config'
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/release'
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: '18'
        check-latest: true

    - name: Install Renovate
      run: npm install -g renovate

    - name: Check Renovate configuraton
      run: renovate-config-validator

  lint:
    - name: 'asdf:install'                                                                                                                                                       
      uses: asdf-vm/actions/install@v2.2.0

    - uses: actions/setup-python@v4

    - name: Init tooling
      run: |
        tflint --init

    - name: Check modules
      uses: pre-commit/action@v3.0.0
      with:
        extra_args: --show-diff-on-failure --all-files
